<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
$_esthelper = $this->helper('Estdevs\Hideprice\Helper\Data');   
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <fieldset class="fieldset">
         <?php if ($block->shouldRenderQuantity()): ?>
             <div class="field qty">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                           data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           />
                </div>
            </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </fieldset>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
    <!-- Start code to hide price -->
        <?php if(!$_esthelper->isCustomerlogin() && $_esthelper->isenable()): ?>
            <?php  $loginbutton='<a  class="action tocart primary" href="'.$block->getUrl('customer/account/login').'">'.$_esthelper->getbuttontext().'</a>';?> 
                <script type="text/javascript">
                    require([
                        'jquery',
                        'domReady!'
                    ], function($) {
                        'use strict';

                        jQuery('.price-box').html('<?php  echo $_esthelper->estmessage();?>');
                        jQuery('.box-tocart .actions').html('<?php  echo $loginbutton;?>');
                        if(jQuery('.prices-tier').length>0) {
                            jQuery('.prices-tier').remove();
                        }

                        if(jQuery('.product-addto-links .tocompare').length>0)
                        {
                            jQuery('.product-addto-links .tocompare').remove();
                        }
                    });

                </script>
        <?php endif; ?>
 <!-- Start code to hide price -->
  